package com.ppmp.uniware.model;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2018-11-22T18:21:56.352+05:30
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://uniware.unicommerce.com/services/", name = "Unicommerce")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface Unicommerce {

    @WebMethod(operationName = "MarkShippingPackageDelivered")
    @WebResult(name = "MarkShippingPackageDeliveredResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "MarkShippingPackageDeliveredResponse")
    public MarkShippingPackageDeliveredResponse markShippingPackageDelivered(
            @WebParam(partName = "MarkShippingPackageDeliveredRequest", name = "MarkShippingPackageDeliveredRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    MarkShippingPackageDeliveredRequest markShippingPackageDeliveredRequest
    );

    @WebMethod(operationName = "CancelSaleOrder")
    @WebResult(name = "CancelSaleOrderResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "CancelSaleOrderResponse")
    public ServiceResponse cancelSaleOrder(
            @WebParam(partName = "CancelSaleOrderRequest", name = "CancelSaleOrderRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    CancelSaleOrderRequest cancelSaleOrderRequest
    );

    @WebMethod(operationName = "CreateFacility")
    @WebResult(name = "CreateFacilityResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "CreateFacilityResponse")
    public CreateFacilityResponse createFacility(
            @WebParam(partName = "CreateFacilityRequest", name = "CreateFacilityRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    CreateFacilityRequest createFacilityRequest
    );

    @WebMethod(operationName = "EditFacility")
    @WebResult(name = "EditFacilityResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "EditFacilityResponse")
    public EditFacilityResponse editFacility(
            @WebParam(partName = "EditFacilityRequest", name = "EditFacilityRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    EditFacilityRequest editFacilityRequest
    );

    @WebMethod(operationName = "ReceiveReversePickupFromRetail")
    @WebResult(name = "ReceiveReversePickupFromRetailResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "ReceiveReversePickupFromRetailResponse")
    public ReceiveReversePickupFromRetailResponse receiveReversePickupFromRetail(
            @WebParam(partName = "ReceiveReversePickupFromRetailRequest", name = "ReceiveReversePickupFromRetailRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    ReceiveReversePickupFromRetailRequest receiveReversePickupFromRetailRequest
    );

    @WebMethod(operationName = "CreateOrEditFacilityItemType")
    @WebResult(name = "CreateOrEditFacilityItemTypeResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "CreateOrEditFacilityItemTypeResponse")
    public ServiceResponse createOrEditFacilityItemType(
            @WebParam(partName = "CreateOrEditFacilityItemTypeRequest", name = "CreateOrEditFacilityItemTypeRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    CreateOrEditFacilityItemTypeRequest createOrEditFacilityItemTypeRequest
    );

    @WebMethod(operationName = "EditChannelItemTypePrice")
    @WebResult(name = "EditChannelItemTypePriceResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "EditChannelItemTypePriceResponse")
    public EditChannelItemTypePriceResponse editChannelItemTypePrice(
            @WebParam(partName = "EditChannelItemTypePriceRequest", name = "EditChannelItemTypePriceRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    EditChannelItemTypePriceRequest editChannelItemTypePriceRequest
    );

    @WebMethod(operationName = "EditSaleOrderAddress")
    @WebResult(name = "EditSaleOrderAddressResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "EditSaleOrderAddressResponse")
    public ServiceResponse editSaleOrderAddress(
            @WebParam(partName = "EditSaleOrderAddressRequest", name = "EditSaleOrderAddressRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    EditSaleOrderAddressRequest editSaleOrderAddressRequest
    );

    @WebMethod(operationName = "GetSaleOrder")
    @WebResult(name = "GetSaleOrderResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "GetSaleOrderResponse")
    public GetSaleOrderResponse getSaleOrder(
            @WebParam(partName = "GetSaleOrderRequest", name = "GetSaleOrderRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    GetSaleOrderRequest getSaleOrderRequest
    );

    @WebMethod(operationName = "GetItemTypeInventory")
    @WebResult(name = "GetItemTypeInventoryResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "GetItemTypeInventoryResponse")
    public GetItemTypeInventoryResponse getItemTypeInventory(
            @WebParam(partName = "GetItemTypeInventoryRequest", name = "GetItemTypeInventoryRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    GetItemTypeInventoryRequest getItemTypeInventoryRequest
    );

    @WebMethod(operationName = "SearchItemTypes")
    @WebResult(name = "SearchItemTypesResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "SearchItemTypesResponse")
    public SearchItemTypesResponse searchItemTypes(
            @WebParam(partName = "SearchItemTypesRequest", name = "SearchItemTypesRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    SearchItemTypesRequest searchItemTypesRequest
    );

    @WebMethod(operationName = "CreateASN")
    @WebResult(name = "CreateASNResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "CreateASNResponse")
    public CreateASNResponse createASN(
            @WebParam(partName = "CreateASNRequest", name = "CreateASNRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    CreateASNRequest createASNRequest
    );

    @WebMethod(operationName = "CreateSaleOrder")
    @WebResult(name = "CreateSaleOrderResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "CreateSaleOrderResponse")
    public ServiceResponse createSaleOrder(
            @WebParam(partName = "CreateSaleOrderRequest", name = "CreateSaleOrderRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    CreateSaleOrderRequest createSaleOrderRequest
    );

    @WebMethod(operationName = "CreatePutawayList")
    @WebResult(name = "CreatePutawayListResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "CreatePutawayListResponse")
    public CreatePutawayListResponse createPutawayList(
            @WebParam(partName = "CreatePutawayListRequest", name = "CreatePutawayListRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    CreatePutawayListRequest createPutawayListRequest
    );

    @WebMethod(operationName = "CreateInvoiceAndAllocateShippingProvider")
    @WebResult(name = "CreateInvoiceAndAllocateShippingProviderResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "CreateInvoiceAndAllocateShippingProviderResponse")
    public CreateInvoiceAndAllocateShippingProviderResponse createInvoiceAndAllocateShippingProvider(
            @WebParam(partName = "CreateInvoiceAndAllocateShippingProviderRequest", name = "CreateInvoiceAndAllocateShippingProviderRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    CreateInvoiceAndAllocateShippingProviderRequest createInvoiceAndAllocateShippingProviderRequest
    );

    @WebMethod(operationName = "GetBackOrderItems")
    @WebResult(name = "GetBackOrderItemsResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "GetBackOrderItemsResponse")
    public GetBackOrderItemsResponse getBackOrderItems(
            @WebParam(partName = "GetBackOrderItemsRequest", name = "GetBackOrderItemsRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    GetBackOrderItemsRequest getBackOrderItemsRequest
    );

    @WebMethod(operationName = "AddOrEditPurchaseOrderItems")
    @WebResult(name = "AddOrEditPurchaseOrderItemsResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "AddOrEditPurchaseOrderItemsResponse")
    public ServiceResponse addOrEditPurchaseOrderItems(
            @WebParam(partName = "AddOrEditPurchaseOrderItemsRequest", name = "AddOrEditPurchaseOrderItemsRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    AddOrEditPurchaseOrderItemsRequest addOrEditPurchaseOrderItemsRequest
    );

    @WebMethod(operationName = "GetPurchaseOrders")
    @WebResult(name = "GetPurchaseOrdersResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "GetPurchaseOrdersResponse")
    public GetPurchaseOrdersResponse getPurchaseOrders(
            @WebParam(partName = "GetPurchaseOrdersRequest", name = "GetPurchaseOrdersRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    GetPurchaseOrdersRequest getPurchaseOrdersRequest
    );

    @WebMethod(operationName = "CreateOrEditVendorItemType")
    @WebResult(name = "CreateOrEditVendorItemTypeResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "CreateOrEditVendorItemTypeResponse")
    public ServiceResponse createOrEditVendorItemType(
            @WebParam(partName = "CreateOrEditVendorItemTypeRequest", name = "CreateOrEditVendorItemTypeRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    VendorItemType createOrEditVendorItemTypeRequest
    );

    @WebMethod(operationName = "AddOrEditItemLabels")
    @WebResult(name = "AddOrEditItemLabelsResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "AddOrEditItemLabelsResponse")
    public ServiceResponse addOrEditItemLabels(
            @WebParam(partName = "AddOrEditItemLabelsRequest", name = "AddOrEditItemLabelsRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    AddOrEditItemLabelsRequest addOrEditItemLabelsRequest
    );

    @WebMethod(operationName = "CreateExportJob")
    @WebResult(name = "CreateExportJobResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "CreateExportJobResponse")
    public CreateExportJobResponse createExportJob(
            @WebParam(partName = "CreateExportJobRequest", name = "CreateExportJobRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    CreateExportJobRequest createExportJobRequest
    );

    @WebMethod(operationName = "GetServiceability")
    @WebResult(name = "GetServiceabilityResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "GetServiceabilityResponse")
    public GetServiceabilityResponse getServiceability(
            @WebParam(partName = "GetServiceabilityRequest", name = "GetServiceabilityRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    GetServiceabilityRequest getServiceabilityRequest
    );

    @WebMethod(operationName = "EditSaleOrderMetadata")
    @WebResult(name = "EditSaleOrderMetadataResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "EditSaleOrderMetadataResponse")
    public ServiceResponse editSaleOrderMetadata(
            @WebParam(partName = "EditSaleOrderMetadataRequest", name = "EditSaleOrderMetadataRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    EditSaleOrderMetadataRequest editSaleOrderMetadataRequest
    );

    @WebMethod(operationName = "AcceptSaleOrderItemAlternate")
    @WebResult(name = "AcceptSaleOrderItemAlternateResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "AcceptSaleOrderItemAlternateResponse")
    public ServiceResponse acceptSaleOrderItemAlternate(
            @WebParam(partName = "AcceptSaleOrderItemAlternateRequest", name = "AcceptSaleOrderItemAlternateRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    AcceptSaleOrderItemAlternateRequest acceptSaleOrderItemAlternateRequest
    );

    @WebMethod(operationName = "HoldSaleOrder")
    @WebResult(name = "HoldSaleOrderResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "HoldSaleOrderResponse")
    public ServiceResponse holdSaleOrder(
            @WebParam(partName = "HoldSaleOrderRequest", name = "HoldSaleOrderRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    HoldSaleOrderRequest holdSaleOrderRequest
    );

    @WebMethod(operationName = "MarkSaleOrderReturned")
    @WebResult(name = "MarkSaleOrderReturnedResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "MarkSaleOrderReturnedResponse")
    public MarkSaleOrderReturnedResponse markSaleOrderReturned(
            @WebParam(partName = "MarkSaleOrderReturnedRequest", name = "MarkSaleOrderReturnedRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    MarkSaleOrderReturnedRequest markSaleOrderReturnedRequest
    );

    @WebMethod(operationName = "CreateInvoiceWithDetails")
    @WebResult(name = "CreateInvoiceWithDetailsResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "CreateInvoiceWithDetailsResponse")
    public CreateInvoiceWithDetailsResponse createInvoiceWithDetails(
            @WebParam(partName = "CreateInvoiceWithDetailsRequest", name = "CreateInvoiceWithDetailsRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    CreateInvoiceWithDetailsRequest createInvoiceWithDetailsRequest
    );

    @WebMethod(operationName = "GetItemDetail")
    @WebResult(name = "GetItemDetailResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "GetItemDetailResponse")
    public GetItemDetailResponse getItemDetail(
            @WebParam(partName = "GetItemDetailRequest", name = "GetItemDetailRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    GetItemDetailRequest getItemDetailRequest
    );

    @WebMethod(operationName = "GetItemTypeDetail")
    @WebResult(name = "GetItemTypeDetailResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "GetItemTypeDetailResponse")
    public GetItemTypeDetailResponse getItemTypeDetail(
            @WebParam(partName = "GetItemTypeDetailRequest", name = "GetItemTypeDetailRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    GetItemTypeDetailRequest getItemTypeDetailRequest
    );

    @WebMethod(operationName = "CreatePutaway")
    @WebResult(name = "CreatePutawayResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "CreatePutawayResponse")
    public CreatePutawayResponse createPutaway(
            @WebParam(partName = "CreatePutawayRequest", name = "CreatePutawayRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    CreatePutawayRequest createPutawayRequest
    );

    @WebMethod(operationName = "EditVendor")
    @WebResult(name = "EditVendorResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "EditVendorResponse")
    public ServiceResponse editVendor(
            @WebParam(partName = "EditVendorRequest", name = "EditVendorRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    EditVendorRequest editVendorRequest
    );

    @WebMethod(operationName = "ModifyPacketSaleOrder")
    @WebResult(name = "ModifyPacketSaleOrderResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "ModifyPacketSaleOrderResponse")
    public ModifyPacketSaleOrderResponse modifyPacketSaleOrder(
            @WebParam(partName = "ModifyPacketSaleOrderRequest", name = "ModifyPacketSaleOrderRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    ModifyPacketSaleOrderRequest modifyPacketSaleOrderRequest
    );

    @WebMethod(operationName = "CreateVendorItemType")
    @WebResult(name = "CreateVendorItemTypeResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "CreateVendorItemTypeResponse")
    public ServiceResponse createVendorItemType(
            @WebParam(partName = "CreateVendorItemTypeRequest", name = "CreateVendorItemTypeRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    VendorItemType createVendorItemTypeRequest
    );

    @WebMethod(operationName = "DispatchShippingPackage")
    @WebResult(name = "DispatchShippingPackageResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "DispatchShippingPackageResponse")
    public DispatchShippingPackageResponse dispatchShippingPackage(
            @WebParam(partName = "DispatchShippingPackageRequest", name = "DispatchShippingPackageRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    DispatchShippingPackageRequest dispatchShippingPackageRequest
    );

    @WebMethod(operationName = "EditScriptConfig")
    @WebResult(name = "EditScriptConfigResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "EditScriptConfigResponse")
    public ServiceResponse editScriptConfig(
            @WebParam(partName = "EditScriptConfigRequest", name = "EditScriptConfigRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    EditScriptConfigRequest editScriptConfigRequest
    );

    @WebMethod(operationName = "AddItemToInflowReceipt")
    @WebResult(name = "AddItemToInflowReceiptResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "AddItemToInflowReceiptResponse")
    public AddItemToInflowReceiptResponse addItemToInflowReceipt(
            @WebParam(partName = "AddItemToInflowReceiptRequest", name = "AddItemToInflowReceiptRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    AddItemToInflowReceiptRequest addItemToInflowReceiptRequest
    );

    @WebMethod(operationName = "GetShippingManifest")
    @WebResult(name = "GetShippingManifestResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "GetShippingManifestResponse")
    public GetShippingManifestResponse getShippingManifest(
            @WebParam(partName = "GetShippingManifestRequest", name = "GetShippingManifestRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    GetShippingManifestRequest getShippingManifestRequest
    );

    @WebMethod(operationName = "CreatePurchaseOrder")
    @WebResult(name = "CreatePurchaseOrderResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "CreatePurchaseOrderResponse")
    public CreatePurchaseOrderResponse createPurchaseOrder(
            @WebParam(partName = "CreatePurchaseOrderRequest", name = "CreatePurchaseOrderRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    CreatePurchaseOrderRequest createPurchaseOrderRequest
    );

    @WebMethod(operationName = "PickShippingPackage")
    @WebResult(name = "PickShippingPackageResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "PickShippingPackageResponse")
    public PickShippingPackageResponse pickShippingPackage(
            @WebParam(partName = "PickShippingPackageRequest", name = "PickShippingPackageRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    PickShippingPackageRequest pickShippingPackageRequest
    );

    @WebMethod(operationName = "CreateInflowReceipt")
    @WebResult(name = "CreateInflowReceiptResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "CreateInflowReceiptResponse")
    public CreateInflowReceiptResponse createInflowReceipt(
            @WebParam(partName = "CreateInflowReceiptRequest", name = "CreateInflowReceiptRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    CreateInflowReceiptRequest createInflowReceiptRequest
    );

    @WebMethod(operationName = "AutoCompletePutaway")
    @WebResult(name = "AutoCompletePutawayResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "AutoCompletePutawayResponse")
    public AutoCompletePutawayResponse autoCompletePutaway(
            @WebParam(partName = "AutoCompletePutawayRequest", name = "AutoCompletePutawayRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    AutoCompletePutawayRequest autoCompletePutawayRequest
    );

    @WebMethod(operationName = "EditShippingPackage")
    @WebResult(name = "EditShippingPackageResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "EditShippingPackageResponse")
    public EditShippingPackageResponse editShippingPackage(
            @WebParam(partName = "EditShippingPackageRequest", name = "EditShippingPackageRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    EditShippingPackageRequest editShippingPackageRequest
    );

    @WebMethod(operationName = "EditSaleOrderItemMetadata")
    @WebResult(name = "EditSaleOrderItemMetadataResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "EditSaleOrderItemMetadataResponse")
    public ServiceResponse editSaleOrderItemMetadata(
            @WebParam(partName = "EditSaleOrderItemMetadataRequest", name = "EditSaleOrderItemMetadataRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    EditSaleOrderItemMetadataRequest editSaleOrderItemMetadataRequest
    );

    @WebMethod(operationName = "CreateGatePass")
    @WebResult(name = "CreateGatePassResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "CreateGatePassResponse")
    public CreateGatePassResponse createGatePass(
            @WebParam(partName = "CreateGatePassRequest", name = "CreateGatePassRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    CreateGatePassRequest createGatePassRequest
    );

    @WebMethod(operationName = "EditCustomer")
    @WebResult(name = "EditCustomerResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "EditCustomerResponse")
    public ServiceResponse editCustomer(
            @WebParam(partName = "EditCustomerRequest", name = "EditCustomerRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    EditCustomerRequest editCustomerRequest
    );

    @WebMethod(operationName = "CreateCustomer")
    @WebResult(name = "CreateCustomerResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "CreateCustomerResponse")
    public ServiceResponse createCustomer(
            @WebParam(partName = "CreateCustomerRequest", name = "CreateCustomerRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    CreateCustomerRequest createCustomerRequest
    );

    @WebMethod(operationName = "MarkItemDamagedOutboundQC")
    @WebResult(name = "MarkItemDamagedOutboundQCResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "MarkItemDamagedOutboundQCResponse")
    public ServiceResponse markItemDamagedOutboundQC(
            @WebParam(partName = "MarkItemDamagedOutboundQCRequest", name = "MarkItemDamagedOutboundQCRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    MarkItemDamagedOutboundQCRequest markItemDamagedOutboundQCRequest
    );

    @WebMethod(operationName = "ApprovePurchaseOrder")
    @Oneway
    public void approvePurchaseOrder(
            @WebParam(partName = "ApprovePurchaseOrderRequest", name = "ApprovePurchaseOrderRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    ApprovePurchaseOrderRequest approvePurchaseOrderRequest
    );

    @WebMethod(operationName = "SwitchSaleOrderItemFacility")
    @WebResult(name = "SwitchSaleOrderItemFacilityResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "SwitchSaleOrderItemFacilityResponse")
    public SwitchSaleOrderItemFacilityResponse switchSaleOrderItemFacility(
            @WebParam(partName = "SwitchSaleOrderItemFacilityRequest", name = "SwitchSaleOrderItemFacilityRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    SwitchSaleOrderItemFacilityRequest switchSaleOrderItemFacilityRequest
    );

    @WebMethod(operationName = "CompletePutaway")
    @WebResult(name = "CompletePutawayResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "CompletePutawayResponse")
    public CompletePutawayResponse completePutaway(
            @WebParam(partName = "CompletePutawayRequest", name = "CompletePutawayRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    CompletePutawayRequest completePutawayRequest
    );

    @WebMethod(operationName = "ReleaseShelf")
    @WebResult(name = "ReleaseShelfResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "ReleaseShelfResponse")
    public ReleaseShelfResponse releaseShelf(
            @WebParam(partName = "ReleaseShelfRequest", name = "ReleaseShelfRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    ReleaseShelfRequest releaseShelfRequest
    );

    @WebMethod(operationName = "EditGatePass")
    @WebResult(name = "EditGatePassResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "EditGatePassResponse")
    public EditGatePassResponse editGatePass(
            @WebParam(partName = "EditGatePassRequest", name = "EditGatePassRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    EditGatePassRequest editGatePassRequest
    );

    @WebMethod(operationName = "SearchSaleOrder")
    @WebResult(name = "SearchSaleOrderResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "SearchSaleOrderResponse")
    public SearchSaleOrderResponse searchSaleOrder(
            @WebParam(partName = "SearchSaleOrderRequest", name = "SearchSaleOrderRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    SearchSaleOrderRequest searchSaleOrderRequest
    );

    @WebMethod(operationName = "AddEditVendorInvoiceItem")
    @WebResult(name = "AddEditVendorInvoiceItemResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "AddEditVendorInvoiceItemResponse")
    public AddEditVendorInvoiceItemResponse addEditVendorInvoiceItem(
            @WebParam(partName = "AddEditVendorInvoiceItemRequest", name = "AddEditVendorInvoiceItemRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    AddEditVendorInvoiceItemRequest addEditVendorInvoiceItemRequest
    );

    @WebMethod(operationName = "CreateApprovedPurchaseOrder")
    @WebResult(name = "CreateApprovedPurchaseOrderResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "CreateApprovedPurchaseOrderResponse")
    public CreateApprovedPurchaseOrderResponse createApprovedPurchaseOrder(
            @WebParam(partName = "CreateApprovedPurchaseOrderRequest", name = "CreateApprovedPurchaseOrderRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    CreateApprovedPurchaseOrderRequest createApprovedPurchaseOrderRequest
    );

    @WebMethod(operationName = "AddShipmentsToBatch")
    @WebResult(name = "AddShipmentsToBatchResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "AddShipmentsToBatchResponse")
    public AddShipmentsToBatchResponse addShipmentsToBatch(
            @WebParam(partName = "AddShipmentsToBatchRequest", name = "AddShipmentsToBatchRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    AddShipmentsToBatchRequest addShipmentsToBatchRequest
    );

    @WebMethod(operationName = "AddItemToGatePass")
    @WebResult(name = "AddItemToGatePassResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "AddItemToGatePassResponse")
    public AddItemToGatePassResponse addItemToGatePass(
            @WebParam(partName = "AddItemToGatePassRequest", name = "AddItemToGatePassRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    AddItemToGatePassRequest addItemToGatePassRequest
    );

    @WebMethod(operationName = "GetPurchaseOrderDetail")
    @WebResult(name = "GetPurchaseOrderDetailResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "GetPurchaseOrderDetailResponse")
    public GetPurchaseOrderDetailResponse getPurchaseOrderDetail(
            @WebParam(partName = "GetPurchaseOrderDetailRequest", name = "GetPurchaseOrderDetailRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    GetPurchaseOrderDetailRequest getPurchaseOrderDetailRequest
    );

    @WebMethod(operationName = "VerifySaleOrder")
    @WebResult(name = "VerifySaleOrderResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "VerifySaleOrderResponse")
    public ServiceResponse verifySaleOrder(
            @WebParam(partName = "VerifySaleOrderRequest", name = "VerifySaleOrderRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    VerifySaleOrderRequest verifySaleOrderRequest
    );

    @WebMethod(operationName = "CreateReversePickup")
    @WebResult(name = "CreateReversePickupResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "CreateReversePickupResponse")
    public CreateReversePickupResponse createReversePickup(
            @WebParam(partName = "CreateReversePickupRequest", name = "CreateReversePickupRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    CreateReversePickupRequest createReversePickupRequest
    );

    @WebMethod(operationName = "GetInventorySnapshot")
    @WebResult(name = "GetInventorySnapshotResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "GetInventorySnapshotResponse")
    public GetInventorySnapshotResponse getInventorySnapshot(
            @WebParam(partName = "GetInventorySnapshotRequest", name = "GetInventorySnapshotRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    GetInventorySnapshotRequest getInventorySnapshotRequest
    );

    @WebMethod(operationName = "UnholdSaleOrderItems")
    @WebResult(name = "UnholdSaleOrderItemsResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "UnholdSaleOrderItemsResponse")
    public ServiceResponse unholdSaleOrderItems(
            @WebParam(partName = "UnholdSaleOrderItemsRequest", name = "UnholdSaleOrderItemsRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    UnholdSaleOrderItemsRequest unholdSaleOrderItemsRequest
    );

    @WebMethod(operationName = "InventoryAdjustment")
    @WebResult(name = "InventoryAdjustmentResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "InventoryAdjustmentResponse")
    public ServiceResponse inventoryAdjustment(
            @WebParam(partName = "InventoryAdjustmentRequest", name = "InventoryAdjustmentRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    InventoryAdjustmentRequest inventoryAdjustmentRequest
    );

    @WebMethod(operationName = "CreateItemType")
    @WebResult(name = "CreateItemTypeResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "CreateItemTypeResponse")
    public ServiceResponse createItemType(
            @WebParam(partName = "CreateItemTypeRequest", name = "CreateItemTypeRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    ItemTypeRequest createItemTypeRequest
    );

    @WebMethod(operationName = "GetInvoiceLabel")
    @WebResult(name = "GetInvoiceLabelResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "GetInvoiceLabelResponse")
    public GetInvoiceLabelResponse getInvoiceLabel(
            @WebParam(partName = "GetInvoiceLabelRequest", name = "GetInvoiceLabelRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    GetInvoiceLabelRequest getInvoiceLabelRequest
    );

    @WebMethod(operationName = "UpdateTrackingStatus")
    @WebResult(name = "UpdateTrackingStatusResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "UpdateTrackingStatusResponse")
    public ServiceResponse updateTrackingStatus(
            @WebParam(partName = "UpdateTrackingStatusRequest", name = "UpdateTrackingStatusRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    UpdateTrackingStatusRequest updateTrackingStatusRequest
    );

    @WebMethod(operationName = "AddNonTraceableGatePassItem")
    @WebResult(name = "AddNonTraceableGatePassItemResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "AddNonTraceableGatePassItemResponse")
    public AddNonTraceableGatePassItemResponse addNonTraceableGatePassItem(
            @WebParam(partName = "AddNonTraceableGatePassItemRequest", name = "AddNonTraceableGatePassItemRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    AddNonTraceableGatePassItemRequest addNonTraceableGatePassItemRequest
    );

    @WebMethod(operationName = "EditItemType")
    @WebResult(name = "EditItemTypeResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "EditItemTypeResponse")
    public ServiceResponse editItemType(
            @WebParam(partName = "EditItemTypeRequest", name = "EditItemTypeRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    ItemTypeRequest editItemTypeRequest
    );

    @WebMethod(operationName = "EditAdvanceShippingNotice")
    @WebResult(name = "EditAdvanceShippingNoticeResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "EditAdvanceShippingNoticeResponse")
    public EditAdvanceShippingNoticeResponse editAdvanceShippingNotice(
            @WebParam(partName = "EditAdvanceShippingNoticeRequest", name = "EditAdvanceShippingNoticeRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    EditAdvanceShippingNoticeRequest editAdvanceShippingNoticeRequest
    );

    @WebMethod(operationName = "VerifySaleOrderItemsPODCode")
    @WebResult(name = "VerifySaleOrderItemsPODCodeResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "VerifySaleOrderItemsPODCodeResponse")
    public VerifySaleOrderItemsPODCodeResponse verifySaleOrderItemsPODCode(
            @WebParam(partName = "VerifySaleOrderItemsPODCodeRequest", name = "VerifySaleOrderItemsPODCodeRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    VerifySaleOrderItemsPODCodeRequest verifySaleOrderItemsPODCodeRequest
    );

    @WebMethod(operationName = "CreateInvoiceBySaleOrderCode")
    @WebResult(name = "CreateInvoiceBySaleOrderCodeResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "CreateInvoiceBySaleOrderCodeResponse")
    public CreateInvoiceBySaleOrderCodeResponse createInvoiceBySaleOrderCode(
            @WebParam(partName = "CreateInvoiceBySaleOrderCodeRequest", name = "CreateInvoiceBySaleOrderCodeRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    CreateInvoiceBySaleOrderCodeRequest createInvoiceBySaleOrderCodeRequest
    );

    @WebMethod(operationName = "GetExportJobStatus")
    @WebResult(name = "GetExportJobStatusResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "GetExportJobStatusResponse")
    public GetExportJobStatusResponse getExportJobStatus(
            @WebParam(partName = "GetExportJobStatusRequest", name = "GetExportJobStatusRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    GetExportJobStatusRequest getExportJobStatusRequest
    );

    @WebMethod(operationName = "UnblockSaleOrderItemsInventory")
    @WebResult(name = "UnblockSaleOrderItemsInventoryResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "UnblockSaleOrderItemsInventoryResponse")
    public UnblockSaleOrderItemsInventoryResponse unblockSaleOrderItemsInventory(
            @WebParam(partName = "UnblockSaleOrderItemsInventoryRequest", name = "UnblockSaleOrderItemsInventoryRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    UnblockSaleOrderItemsInventoryRequest unblockSaleOrderItemsInventoryRequest
    );

    @WebMethod(operationName = "DispatchSaleOrderItems")
    @WebResult(name = "DispatchSaleOrderItemsResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "DispatchSaleOrderItemsResponse")
    public DispatchSaleOrderItemsResponse dispatchSaleOrderItems(
            @WebParam(partName = "DispatchSaleOrderItemsRequest", name = "DispatchSaleOrderItemsRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    DispatchSaleOrderItemsRequest dispatchSaleOrderItemsRequest
    );

    @WebMethod(operationName = "EditVendorItemType")
    @WebResult(name = "EditVendorItemTypeResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "EditVendorItemTypeResponse")
    public ServiceResponse editVendorItemType(
            @WebParam(partName = "EditVendorItemTypeRequest", name = "EditVendorItemTypeRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    VendorItemType editVendorItemTypeRequest
    );

    @WebMethod(operationName = "SearchShippingPackage")
    @WebResult(name = "SearchShippingPackageResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "SearchShippingPackageResponse")
    public SearchShippingPackageResponse searchShippingPackage(
            @WebParam(partName = "SearchShippingPackageRequest", name = "SearchShippingPackageRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    SearchShippingPackageRequest searchShippingPackageRequest
    );

    @WebMethod(operationName = "VerifyShippingPackagePODCode")
    @WebResult(name = "VerifyShippingPackagePODCodeResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "VerifyShippingPackagePODCodeResponse")
    public VerifyShippingPackagePODCodeResponse verifyShippingPackagePODCode(
            @WebParam(partName = "VerifyShippingPackagePODCodeRequest", name = "VerifyShippingPackagePODCodeRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    VerifyShippingPackagePODCodeRequest verifyShippingPackagePODCodeRequest
    );

    @WebMethod(operationName = "GetVendorItemTypes")
    @WebResult(name = "GetVendorItemTypesResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "GetVendorItemTypesResponse")
    public GetVendorItemTypesResponse getVendorItemTypes(
            @WebParam(partName = "GetVendorItemTypesRequest", name = "GetVendorItemTypesRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    GetVendorItemTypesRequest getVendorItemTypesRequest
    );

    @WebMethod(operationName = "AddItemDetails")
    @WebResult(name = "AddItemDetailsResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "AddItemDetailsResponse")
    public AddItemDetailsResponse addItemDetails(
            @WebParam(partName = "AddItemDetailsRequest", name = "AddItemDetailsRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    AddItemDetailsRequest addItemDetailsRequest
    );

    @WebMethod(operationName = "ChangeInvoiceCode")
    @WebResult(name = "ChangeInvoiceCodeResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "ChangeInvoiceCodeResponse")
    public ChangeInvoiceCodeResponse changeInvoiceCode(
            @WebParam(partName = "ChangeInvoiceCodeRequest", name = "ChangeInvoiceCodeRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    ChangeInvoiceCodeRequest changeInvoiceCodeRequest
    );

    @WebMethod(operationName = "UnholdSaleOrder")
    @WebResult(name = "UnholdSaleOrderResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "UnholdSaleOrderResponse")
    public ServiceResponse unholdSaleOrder(
            @WebParam(partName = "UnholdSaleOrderRequest", name = "UnholdSaleOrderRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    UnholdSaleOrderRequest unholdSaleOrderRequest
    );

    @WebMethod(operationName = "GetItemType")
    @WebResult(name = "GetItemTypeResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "GetItemTypeResponse")
    public GetItemTypeResponse getItemType(
            @WebParam(partName = "GetItemTypeRequest", name = "GetItemTypeRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    GetItemTypeRequest getItemTypeRequest
    );

    @WebMethod(operationName = "GetInflowReceipts")
    @WebResult(name = "GetInflowReceiptsResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "GetInflowReceiptsResponse")
    public GetInflowReceiptsResponse getInflowReceipts(
            @WebParam(partName = "GetInflowReceiptsRequest", name = "GetInflowReceiptsRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    GetInflowReceiptsRequest getInflowReceiptsRequest
    );

    @WebMethod(operationName = "CompleteGatePass")
    @WebResult(name = "CompleteGatePassResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "CompleteGatePassResponse")
    public CompleteGatePassResponse completeGatePass(
            @WebParam(partName = "CompleteGatePassRequest", name = "CompleteGatePassRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    CompleteGatePassRequest completeGatePassRequest
    );

    @WebMethod(operationName = "ClosePurchaseOrder")
    @WebResult(name = "ClosePurchaseOrderResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "ClosePurchaseOrderResponse")
    public ServiceResponse closePurchaseOrder(
            @WebParam(partName = "ClosePurchaseOrderRequest", name = "ClosePurchaseOrderRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    ClosePurchaseOrderRequest closePurchaseOrderRequest
    );

    @WebMethod(operationName = "SearchGatePass")
    @WebResult(name = "SearchGatePassResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "SearchGatePassResponse")
    public SearchGatePassResponse searchGatePass(
            @WebParam(partName = "SearchGatePassRequest", name = "SearchGatePassRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    SearchGatePassRequest searchGatePassRequest
    );

    @WebMethod(operationName = "CreateOrEditCategory")
    @WebResult(name = "CreateOrEditCategoryResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "CreateOrEditCategoryResponse")
    public ServiceResponse createOrEditCategory(
            @WebParam(partName = "CreateOrEditCategoryRequest", name = "CreateOrEditCategoryRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    CreateOrEditCategoryRequest createOrEditCategoryRequest
    );

    @WebMethod(operationName = "CreateOrEditItemType")
    @WebResult(name = "CreateOrEditItemTypeResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "CreateOrEditItemTypeResponse")
    public ServiceResponse createOrEditItemType(
            @WebParam(partName = "CreateOrEditItemTypeRequest", name = "CreateOrEditItemTypeRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    ItemTypeRequest createOrEditItemTypeRequest
    );

    @WebMethod(operationName = "GetInflowReceiptDetail")
    @WebResult(name = "GetInflowReceiptDetailResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "GetInflowReceiptDetailResponse")
    public GetInflowReceiptDetailResponse getInflowReceiptDetail(
            @WebParam(partName = "GetInflowReceiptDetailRequest", name = "GetInflowReceiptDetailRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    GetInflowReceiptDetailRequest getInflowReceiptDetailRequest
    );

    @WebMethod(operationName = "CreateInvoice")
    @WebResult(name = "CreateInvoiceResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "CreateInvoiceResponse")
    public CreateInvoiceResponse createInvoice(
            @WebParam(partName = "CreateInvoiceRequest", name = "CreateInvoiceRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    CreateInvoiceRequest createInvoiceRequest
    );

    @WebMethod(operationName = "HoldSaleOrderItems")
    @WebResult(name = "HoldSaleOrderItemsResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "HoldSaleOrderItemsResponse")
    public ServiceResponse holdSaleOrderItems(
            @WebParam(partName = "HoldSaleOrderItemsRequest", name = "HoldSaleOrderItemsRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    HoldSaleOrderItemsRequest holdSaleOrderItemsRequest
    );

    @WebMethod(operationName = "MarkSaleOrderItemsDelivered")
    @WebResult(name = "MarkSaleOrderItemsDeliveredResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "MarkSaleOrderItemsDeliveredResponse")
    public MarkSaleOrderItemsDeliveredResponse markSaleOrderItemsDelivered(
            @WebParam(partName = "MarkSaleOrderItemsDeliveredRequest", name = "MarkSaleOrderItemsDeliveredRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    MarkSaleOrderItemsDeliveredRequest markSaleOrderItemsDeliveredRequest
    );

    @WebMethod(operationName = "CreateBatch")
    @WebResult(name = "CreateBatchResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "CreateBatchResponse")
    public CreateBatchResponse createBatch(
            @WebParam(partName = "CreateBatchRequest", name = "CreateBatchRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    CreateBatchRequest createBatchRequest
    );

    @WebMethod(operationName = "GetTaxTypeConfiguration")
    @WebResult(name = "GetTaxTypeConfigurationResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "GetTaxTypeConfigurationResponse")
    public GetTaxTypeConfigurationResponse getTaxTypeConfiguration(
            @WebParam(partName = "GetTaxTypeConfigurationRequest", name = "GetTaxTypeConfigurationRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    GetTaxTypeConfigurationRequest getTaxTypeConfigurationRequest
    );

    @WebMethod(operationName = "CreateVendor")
    @WebResult(name = "CreateVendorResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "CreateVendorResponse")
    public ServiceResponse createVendor(
            @WebParam(partName = "CreateVendorRequest", name = "CreateVendorRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    CreateVendorRequest createVendorRequest
    );

    @WebMethod(operationName = "AddOrEditShippingProviderLocation")
    @WebResult(name = "AddOrEditShippingProviderLocationResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "AddOrEditShippingProviderLocationResponse")
    public AddOrEditShippingProviderLocationResponse addOrEditShippingProviderLocation(
            @WebParam(partName = "AddOrEditShippingProviderLocationRequest", name = "AddOrEditShippingProviderLocationRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    AddOrEditShippingProviderLocationRequest addOrEditShippingProviderLocationRequest
    );

    @WebMethod(operationName = "CreateSaleOrderItemAlternate")
    @WebResult(name = "CreateSaleOrderItemAlternateResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "CreateSaleOrderItemAlternateResponse")
    public ServiceResponse createSaleOrderItemAlternate(
            @WebParam(partName = "CreateSaleOrderItemAlternateRequest", name = "CreateSaleOrderItemAlternateRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    CreateSaleOrderItemAlternateRequest createSaleOrderItemAlternateRequest
    );

    @WebMethod(operationName = "AddReversePickupSaleOrderItemsToPutaway")
    @WebResult(name = "AddReversePickupSaleOrderItemsToPutawayResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "AddReversePickupSaleOrderItemsToPutawayResponse")
    public AddReversePickupSaleOrderItemsToPutawayResponse addReversePickupSaleOrderItemsToPutaway(
            @WebParam(partName = "AddReversePickupSaleOrderItemsToPutawayRequest", name = "AddReversePickupSaleOrderItemsToPutawayRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    AddReversePickupSaleOrderItemsToPutawayRequest addReversePickupSaleOrderItemsToPutawayRequest
    );

    @WebMethod(operationName = "SplitShippingPackage")
    @WebResult(name = "SplitShippingPackageResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "SplitShippingPackageResponse")
    public SplitShippingPackageResponse splitShippingPackage(
            @WebParam(partName = "SplitShippingPackageRequest", name = "SplitShippingPackageRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    SplitShippingPackageRequest splitShippingPackageRequest
    );

    @WebMethod(operationName = "CreateVendorCreditInvoice")
    @WebResult(name = "CreateVendorCreditInvoiceResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "CreateVendorCreditInvoiceResponse")
    public CreateVendorCreditInvoiceResponse createVendorCreditInvoice(
            @WebParam(partName = "CreateVendorCreditInvoiceRequest", name = "CreateVendorCreditInvoiceRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    CreateVendorCreditInvoiceRequest createVendorCreditInvoiceRequest
    );

    @WebMethod(operationName = "GetInvoiceDetails")
    @WebResult(name = "GetInvoiceDetailsResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "GetInvoiceDetailsResponse")
    public GetInvoiceDetailsResponse getInvoiceDetails(
            @WebParam(partName = "GetInvoiceDetailsRequest", name = "GetInvoiceDetailsRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    GetInvoiceDetailsRequest getInvoiceDetailsRequest
    );

    @WebMethod(operationName = "AddOrEditNonTraceableGatePassItem")
    @WebResult(name = "AddOrEditNonTraceableGatePassItemResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "AddOrEditNonTraceableGatePassItemResponse")
    public AddOrEditNonTraceableGatePassItemResponse addOrEditNonTraceableGatePassItem(
            @WebParam(partName = "AddOrEditNonTraceableGatePassItemRequest", name = "AddOrEditNonTraceableGatePassItemRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    AddOrEditNonTraceableGatePassItemRequest addOrEditNonTraceableGatePassItemRequest
    );

    @WebMethod(operationName = "SetSaleOrderPriority")
    @WebResult(name = "SetSaleOrderPriorityResponse", targetNamespace = "http://uniware.unicommerce.com/services/", partName = "SetSaleOrderPriorityResponse")
    public SetSaleOrderPriorityResponse setSaleOrderPriority(
            @WebParam(partName = "SetSaleOrderPriorityRequest", name = "SetSaleOrderPriorityRequest", targetNamespace = "http://uniware.unicommerce.com/services/")
                    SetSaleOrderPriorityRequest setSaleOrderPriorityRequest
    );
}
